[api]
ip = "0.0.0.0"
port = 8000
username = "server"
password = "secret_key"

[database]
path = "database.sqlite3"

[docker]
challenge_path = "/challenges"

[ssh]
keyfile = "keys/key"

[servers.default]
port = "22"
user = "root"
path = "/deployment"
