[api]
ip = "localhost"
port = 8000

[docker]
compose_path = "../../CTF/VUCTF-2024-Challenges/docker-compose.yml"

[ssh]
keyfile = "keys/key"

[servers.default]
port = "22"
user = "root"
path = "/deployment"

[servers.node1]
ip = "10.191.0.206"
port = "22"
user = "root"
path = "/srv"

[servers.node2]
ip = "10.191.0.133"

[servers.node3]
ip = "10.191.0.222"
