[api]
ip = "0.0.0.0"
port = 8000

[database]
path = "database.sqlite3"

[docker]
compose_path = "/challenges/docker-compose.yml"

[ssh]
keyfile = "keys/key"

[servers.default]
port = "22"
user = "root"
path = "/deployment"

[servers.node1]
ip = "10.191.0.205"
port = "22"
user = "root"
path = "/srv"

[servers.node2]
ip = "10.191.0.133"

[servers.node3]
ip = "10.191.0.222"
