services:
  instancer:
    build:
      context: .
    volumes:
      - ./data/challenges/Challenges/:/challenges
      - ./data/instancer/keys/:/app/keys
      - ./data/instancer/config.toml:/app/config.toml