services:
  instancer:
    container_name: instancer
    build:
      context: .
    volumes:
      - ./challenges/Challenges/:/challenges
      - ./keys/:/app/keys
      - ./config.toml:/app/config.toml
    ports:
      - 8000:8000
